### ISSUE TITLE
terminate called after throwing an instance of 'std::out_of_range'

### ISSUE THREAD

**Issue by Nova555** [ibrahimjad/tangent_planner#1] opened 2020-05-05 01:40 UTC
[ INFO] [1588642723.717567057]: The planner is initialized properly!
[ INFO] [1588642723.912407785]: Recovery behavior will clear layer 'obstacles'
[ INFO] [1588642723.916706629]: Recovery behavior will clear layer 'obstacles'
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 32744) >= this->size() (which is 667)
[stdr_move_base-7] process has died [pid 3537, exit code -6, cmd /home/nova/catkin_ws/devel/lib/move_base/move_base /cmd_vel:=/robot0/cmd_vel /odom:=/robot0/odom /map:=/amcl/map __name:=stdr_move_base __log:=/home/nova/.ros/log/2665533a-8e71-11ea-96b4-c0b8833d15e9/stdr_move_base-7.log].
log file: /home/nova/.ros/log/2665533a-8e71-11ea-96b4-c0b8833d15e9/stdr_move_base-7*.log

**Comment by ibrahimjad** [comment] 2020-05-05 10:32
Thanks for reporting this. The planner is designed to work with the Turtlebot3 and its LIDAR. The LIDAR has a range from 0 to 2 pi where 0 radian gives the distance infront of the robot with a resolution of 1 degree. ie 360 values.

I am assuming that the issue happened because of a function that converts the angle to laser index. What is the range of your LIDAR and what is the resolution?

**Comment by Nova555** [comment] 2020-05-05 11:04
Thank you for your reply. The range of LIDAR is [-pi/2, pi/2]. The angle_increment is 0.25 deg. 
 Do I need to change function 'angleToLaserIndex'

**Comment by ibrahimjad** [comment] 2020-05-05 19:32
Hi, yeah. The issue is the angleToLaserIndex. An update with a fix has been pushed. Please confirm if it is working so i can close the issue.

**Comment by Nova555** [comment] 2020-05-06 03:28
The 'index' of line 348-th is even in my planner, ie [0 2 4 ... 716 718 0 722]. But I use the Turtlebot3, the 'index' is  continuous, ie [0 1 2 ... 358].  I'm going to change the 2*pi to pi in line 544-th. It's working. But the car passes the goal point(rviz's 2D Nav Goal ), the error also is "'std::out_of_range'"

**Comment by ibrahimjad** [comment] 2020-05-06 06:02
Did it become even after you changed 2pi to pi in line 544-th?
If yes, can you change it back and change line 548 to

index = (index == laser_msg_->ranges.size() - 1) ? 0 : index;

Line 544 is used to map the range from whatever range you use to the range 0 to 2pi which I am working with, so it shouldn't be the issue.

If that does not work can you print the value of index on line 549 inside the if statement and line 550 routside it and post the result?

**Comment by Nova555** [comment] 2020-05-06 06:43
The range of LIDAR is [-pi/2, pi/2]. If line 544-th using 2pi, range of laser(pi) is mapping to 2pi.  However, the obstacles scanned by the laser can only be in the range of [-pi, pi].

**Comment by ibrahimjad** [comment] 2020-05-06 06:53
It is assumed in all the functions that the range is from 0 to 2pi, so the mapping is needed and is only used to get the index. So you do need to map the range.

**Comment by ibrahimjad** [comment] 2020-05-06 07:03
Unfortunattly, i won't be able to help at this time, but will try to fix the issue at some other point as soon as i can.
What type of robot are you using? Perhaps i can simulate it.

**Comment by Nova555** [comment] 2020-05-06 07:05
<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" 
 	xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    	xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    	xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
	name="robot1_xacro">


	<xacro:property name="length_wheel" value="0.05" />
	<xacro:property name="radius_wheel" value="0.05" />
	<xacro:property name="camera_link" value="0.05" /> 
	<xacro:macro name="default_inertial" params="mass">
               <inertial>
                       <mass value="${mass}" />
                       <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                                iyy="1.0" iyz="0.0"
                                izz="1.0" />
               </inertial>
	</xacro:macro>

	<link name="base_footprint">
   		<visual>
			<geometry>
      				<box size="0.001 0.001 0.001"/>
     			</geometry>
			<origin rpy="0 0 0" xyz="0 0 0"/>
   		</visual>
		<xacro:default_inertial mass="0.0001"/>
 	</link>
 	<xacro:include filename="$(find robot1_description)/urdf/robot.gazebo" />
 
	<gazebo reference="base_footprint">
		<material>Gazebo/Green</material>
		<turnGravityOff>false</turnGravityOff>
	</gazebo>

	<joint name="base_footprint_joint" type="fixed">
		<origin xyz="0 0 0" />
		<parent link="base_footprint" />
		<child link="base_link" />
	</joint>


	<link name="base_link">
   		<visual>
			<geometry>
      				<box size="0.2 .3 .1"/>
     			</geometry>
			<origin rpy="0 0 1.54" xyz="0 0 0.05"/>
			<material name="white">
				<color rgba="1 1 1 1"/>
			</material>
   		</visual>
		<collision>
			<geometry>
       				<box size="0.2 .3 0.1"/>
			</geometry>
		</collision>
		<xacro:default_inertial mass="10"/>
 	</link>

 	<link name="wheel_1">
   		<visual>
     			<geometry>
       				<cylinder length="${length_wheel}" radius="${radius_wheel}"/>
     			</geometry>
			
			<origin rpy="0 0 0" xyz="0 0 0"/>
   			<material name="black">
				<color rgba="0 0 0 1"/>
			</material>
		</visual>
		<collision>
			<geometry>
       				<cylinder length="${length_wheel}" radius="${radius_wheel}"/>
			</geometry>
		</collision>
		<xacro:default_inertial mass="1"/>
 	</link>

 	<link name="wheel_2">
   		<visual>
     			<geometry>
       				<cylinder length="${length_wheel}" radius="${radius_wheel}"/>
     			</geometry>
			
			<origin rpy="0 0 0" xyz="0 0 0"/>
   			<material name="black"/>
   		</visual>
		<collision>
			<geometry>
       				<cylinder length="${length_wheel}" radius="${radius_wheel}"/>
			</geometry>
		</collision>
		<xacro:default_inertial mass="1"/>

 	</link>
    
 	<link name="wheel_3">
   		<visual>
     			<geometry>
       				<cylinder length="${length_wheel}" radius="${radius_wheel}"/>
     			</geometry>
			

			<origin rpy="0 0 0" xyz="0 0 0"/>
   			<material name="black"/>
   		</visual>
		<collision>
			<geometry>
       				<cylinder length="${length_wheel}" radius="${radius_wheel}"/>
			</geometry>
		</collision>
		<xacro:default_inertial mass="1"/>
 	</link>

 	<link name="wheel_4">
   		<visual>
     			<geometry>
       				<cylinder length="${length_wheel}" radius="${radius_wheel}"/>
     			</geometry>
		
			<origin rpy="0 0 0" xyz="0 0 0" />
   			<material name="black"/>
   		</visual>
		<collision>
			<geometry>
       				<cylinder length="${length_wheel}" radius="${radius_wheel}"/>
			</geometry>
		</collision>
		<xacro:default_inertial mass="1"/>

 	</link>



 <joint name="base_to_wheel1" type="continuous">
   <parent link="base_link"/>
   <child link="wheel_1"/>
   <origin rpy="-1.5707 0 0" xyz="0.1 0.15 0"/>
   <axis xyz="0 0 1" />
 </joint>

 <joint name="base_to_wheel2" type="continuous">
   <axis xyz="0 0 1" />
   <anchor xyz="0 0 0" />
   <limit effort="100" velocity="100" />
   <parent link="base_link"/>
   <child link="wheel_2"/>
   <origin rpy="-1.5707 0 0" xyz="-0.1 0.15 0"/>
</joint>

 <joint name="base_to_wheel3" type="continuous">
   <parent link="base_link"/>
   <axis xyz="0 0 1" />
   <child link="wheel_3"/>
   <origin rpy="-1.5707 0 0" xyz="0.1 -0.15 0"/>
 </joint>

 <joint name="base_to_wheel4" type="continuous">
   <parent link="base_link"/>
   <axis xyz="0 0 1" />
   <child link="wheel_4"/>
   <origin rpy="-1.5707 0 0" xyz="-0.1 -0.15 0"/>
 </joint>
  
  <joint name="camera_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0.125 0 0.125" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="camera_link"/>
  </joint>

  
  <link name="camera_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.05 0.05 0.05"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.05 0.05 0.05"/>
      </geometry>
      <material name="red">
	<color rgba="1 0 0 1"/>
      </material>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>



  
  <joint name="hokuyo_joint" type="fixed">
    <origin xyz="0.125 0.05 0.125" rpy="0 0 0"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" />
    <child link="hokuyo_link"/>
  </joint>

  
  <link name="hokuyo_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://robot1_description/meshes/hokuyo.dae"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  
<gazebo>
  <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
    <updateRate>100.0</updateRate>
    <robotNamespace>/</robotNamespace>
    <leftFrontJoint>base_to_wheel1</leftFrontJoint>
    <rightFrontJoint>base_to_wheel3</rightFrontJoint>
    <leftRearJoint>base_to_wheel2</leftRearJoint>
    <rightRearJoint>base_to_wheel4</rightRearJoint>
    <wheelSeparation>4</wheelSeparation>
    <wheelDiameter>0.1</wheelDiameter>
    <robotBaseFrame>base_footprint</robotBaseFrame>
    <torque>1</torque>
    <topicName>cmd_vel</topicName>
    <broadcastTF>0</broadcastTF>
  </plugin>
</gazebo>


</robot>

**Comment by Nova555** [comment] 2020-05-06 07:08
https://github.com/AaronMR/Learning_ROS_for_Robotics_Programming_2nd_edition/tree/indigo-devel

**Comment by Nova555** [comment] 2020-05-06 07:09
It's in chapter9_tutorials

**Comment by ibrahimjad** [comment] 2020-05-06 09:18
I think you can fix this by changing the range of your lidar from  (-pi/2, pi/2) to (-pi, pi)

The algorithm assumes that you have a 360 degrees lidar

**Comment by Nova555** [comment] 2020-05-06 09:44
Whether this algorithm can be fixed by two discontinuous points, such as -pi/2 and pi/2. ei.., there's always b barrier behind the roboot.

**Comment by ibrahimjad** [comment] 2020-05-06 21:09
Not sure what you mean by that. But i will fix the issue when I can. Though i can't promise a fix within this month as i have exams.

I will close the issue but will push an update to this that considers LIDAR ranges that are less than 360 degrees.

**Closed as completed** 2020-05-06 21:15 UTC
